Repository bowtie-co/houndstooth-ui, pull requests merged in 2019-03, with the labels that each got.

#4 remove unused props
  src/components/organisms/RecursiveFields/FieldSingle.jsx
Labels: bug

#5 Add /i to ext regex for case-insensitive test
  src/components/molecules/Field/FileUpload/FileUploadContainer.jsx
Labels: bug

#7 Bug/164449016/yml ext ace
  package-lock.json
  src/components/atoms/TextEditor/TextEditor.jsx
  src/helpers/lists.js
Labels: bug

#13 add scroll to top
  package-lock.json
  package.json
  src/components/organisms/ItemList/ItemListContainer.jsx
Labels: enhancement

#14 Using sdk
  README.md
  package-lock.json
  package.json
  src/components/ecosystems/Collections/CollectionsContainer.jsx
  src/components/ecosystems/FileTree/FileTreeContainer.jsx
  src/components/ecosystems/Repo/RepoContainer.jsx
  src/components/ecosystems/Users/UsersContainer.jsx
  src/components/environments/App/AppContainer.jsx
  src/components/organisms/RepoSelect/RepoSelectContainer.jsx
  src/components/organisms/TinyMCE/TinyMCEContainer.jsx
  src/helpers/withQueryParams.jsx
  src/lib/api.js
  src/lib/github.js
  src/lib/index.js
  src/lib/jekyll.js
Labels: enhancement

#16 Feature/164637136/logout on 401
  config/jest.js
  package-lock.json
  package.json
  src/components/environments/App/AppContainer.jsx
  src/components/environments/Auth/Auth.jsx
Labels: bug, enhancement

#17 Reload collections on change of branch
  src/components/ecosystems/FileTree/FileTreeContainer.jsx
  src/components/ecosystems/Repo/RepoContainer.jsx
Labels: enhancement

#18 removing queryParams from sdk params
  src/components/ecosystems/Repo/RepoContainer.jsx
Labels: bug

#19 Rename Collection Item
  package-lock.json
  package.json
  src/components/atoms/TextEditor/TextEditor.jsx
  src/components/atoms/Title/Title.jsx
  src/components/ecosystems/Collections/CollectionsContainer.jsx
  src/components/molecules/RenameFileModal/RenameFileModal.jsx
  src/components/molecules/RenameFileModal/index.js
  src/components/molecules/index.js
  src/components/organisms/ItemForm/ItemForm.jsx
  src/components/organisms/ItemForm/ItemFormContainer.jsx
Labels: enhancement

#21 Rename collection item on different branches
  src/components/ecosystems/Collections/CollectionsContainer.jsx
Labels: enhancement

#24 Bug/164878989/content break
  package-lock.json
  package.json
Labels: bug

#26 commit changes btn is now using absolute path.
  src/components/molecules/RepoControls/RepoControls.jsx
Labels: bug

#28 Replace reference of markdown to body
  package-lock.json
  package.json
  src/components/ecosystems/Collections/CollectionsContainer.jsx
  src/components/organisms/ItemForm/ItemForm.jsx
Labels: bug, requires SDK merge
