Repository bowtie-co/houndstooth-ui, pull requests merged in 2019-06, with the labels that each got.

#49 Feature/166551469/duplicate collection item
  src/components/ecosystems/Collections/CollectionsContainer.jsx
  src/components/organisms/ItemForm/ItemForm.jsx
Labels: enhancement

#51 Misc bug fixes
  src/components/molecules/Field/FileUpload/FileUploadContainer.jsx
  src/components/organisms/ItemList/ItemListContainer.jsx
  src/components/organisms/RepoSelect/RepoSelect.jsx
  src/lib/notifier.js
Labels: bug

#50 Display error notifier & return rejected promise with error
  src/components/ecosystems/Collections/CollectionsContainer.jsx
Labels: enhancement

#47 Feature/dark mode
  package-lock.json
  package.json
  src/components/molecules/Darkmode/Darkmode.jsx
  src/components/molecules/Darkmode/DarkmodeContainer.jsx
  src/components/molecules/Darkmode/index.js
  src/components/molecules/index.js
  src/components/organisms/Header/Header.jsx
  src/helpers/withFormatting.jsx
  src/scss/Loading.css
  src/scss/environments/environments.scss
  src/scss/index.scss
  src/scss/molecules/molecules.scss
  src/scss/organisms/Header.scss
Labels: enhancement

#52 enhancement/166551379/invert blue items
  src/components/atoms/Logout/Logout.jsx
  src/components/molecules/Darkmode/DarkmodeContainer.jsx
Labels: enhancement

#55 Poll for dev server
  config/devServer.js
  craco.config.js
Labels: bug, enhancement

#56 Update detection for date, time, and color fields
  src/components/molecules/Field/FieldContainer.jsx
Labels: bug
